dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

sudo: required

services:
  - docker

before_install:
- docker pull cassandra
- docker run --name cassandra -p 9042:9042 -d cassandra:latest
install:
  - make bootstrap
# command to run tests
script:
  -  make test
