# dist: xenial
language: python
python:
  - "3.6"
  # - "3.7"

sudo: required

services:
  - cassandra

install:
  - make bootstrap
# command to run tests
# before_script:
#   - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
#   - sudo service cassandra start
script:
  -  make test

after_success:
  - codecov -v
